// examples/lit/createThrottledValue/src/main.ts
import { LitElement, html } from 'lit'
import { styleMap } from 'lit/directives/style-map.js'
import { TanStackDevtoolsCore } from '@tanstack/devtools'
import { pacerDevtoolsPlugin } from '@tanstack/pacer-devtools'
import { createThrottledValue } from '@tanstack/lit-pacer/throttler'

class Counter extends LitElement {
  static properties = { instantCount: { state: true } }
  instantCount = 0
  increment = () => {
    this.instantCount = this.instantCount + 1
  }
  throttledCountResult = createThrottledValue(
    this,
    () => this.instantCount,
    () => ({
      wait: 1000,
      // enabled: () => instantCount > 2, // optional, defaults to true
    }),
    (state) => state,
  )
  throttledCount = this.throttledCountResult[0]
  override createRenderRoot() {
    return this
  }
  override render() {
    return html`<div>
      <h1>TanStack Pacer createThrottledValue Example 1</h1>
      <table>
        <tbody>
          <tr>
            <td>Instant Count:</td>
            <td>${this.instantCount}</td>
          </tr>
          <tr>
            <td>Throttled Count:</td>
            <td>${this.throttledCount()}</td>
          </tr>
        </tbody>
      </table>
      <div><button @click=${this.increment}>Increment</button></div>
    </div>`
  }
}
customElements.define('pacer-counter', Counter)
class Search extends LitElement {
  static properties = { instantSearch: { state: true } }
  instantSearch = ''
  throttledSearchResult = createThrottledValue(
    this,
    () => this.instantSearch,
    () => ({
      wait: 1000,
      // enabled: instantSearch.length > 2, // optional, defaults to true
    }),
    (state) => state,
  )
  throttledSearch = this.throttledSearchResult[0]
  handleSearchChange = (e: Event) => {
    this.instantSearch = (e.target as HTMLInputElement).value
  }
  override createRenderRoot() {
    return this
  }
  override render() {
    return html`<div>
      <h1>TanStack Pacer createThrottledValue Example 2</h1>
      <div>
        <input
          type="search"
          .value=${this.instantSearch}
          @input=${this.handleSearchChange}
          placeholder="Type to search..."
          style=${styleMap({ width: '100%' })}
        />
      </div>
      <table>
        <tbody>
          <tr>
            <td>Instant Search:</td>
            <td>${this.instantSearch}</td>
          </tr>
          <tr>
            <td>Throttled Search:</td>
            <td>${this.throttledSearch()}</td>
          </tr>
        </tbody>
      </table>
    </div>`
  }
}
customElements.define('pacer-search', Search)
class Range extends LitElement {
  static properties = {
    submittedCount: { state: true },
    currentValue: { state: true },
  }
  submittedCount = 1
  currentValue = 50
  throttlerResult = createThrottledValue(
    this,
    () => this.currentValue,
    () => ({
      wait: 250,
    }),
    (state) => state,
  )
  throttledValue = this.throttlerResult[0]
  throttler = this.throttlerResult[1]
  handleRangeChange = (e: Event) => {
    const newValue = parseInt((e.target as HTMLInputElement).value, 10)
    this.currentValue = newValue
    this.submittedCount = this.submittedCount + 1
  }
  override createRenderRoot() {
    return this
  }
  override render() {
    return html`<div>
      <h1>TanStack Pacer createThrottledValue Example 3</h1>
      <div style=${styleMap({ marginBottom: '20px' })}>
        <label
          >Current Range:<input
            type="range"
            min="0"
            max="100"
            .value=${this.currentValue}
            @input=${this.handleRangeChange}
            style=${styleMap({ width: '100%' })}
          /><span>${this.currentValue}</span></label
        >
      </div>
      <div style=${styleMap({ marginBottom: '20px' })}>
        <label
          >Throttled Range (Readonly):<input
            type="range"
            min="0"
            max="100"
            .value=${this.throttledValue()}
            disabled
            style=${styleMap({ width: '100%' })}
          /><span>${this.throttledValue()}</span></label
        >
      </div>
      <table>
        <tbody>
          <tr>
            <td>Values Submitted:</td>
            <td>${this.submittedCount}</td>
          </tr>
          <tr>
            <td>Throttled Execution Count:</td>
            <td>${this.throttler.state.executionCount}</td>
          </tr>
          <tr>
            <td>Saved Executions:</td>
            <td>
              ${this.submittedCount - this.throttler.state.executionCount}
              (${
                this.submittedCount > 0
                  ? (
                      ((this.submittedCount -
                        this.throttler.state.executionCount) /
                        this.submittedCount) *
                      100
                    ).toFixed(2)
                  : 0
              }%
              Reduction in execution calls)
            </td>
          </tr>
        </tbody>
      </table>
      <div style=${styleMap({ color: '#666', fontSize: '0.9em' })}>
        <p>Throttled to 1 update per 250ms</p>
      </div>
      <pre style=${styleMap({ marginTop: '20px' })}>
${JSON.stringify(this.throttler.state, null, 2)}</pre>
    </div>`
  }
}
customElements.define('pacer-range', Range)
class Example extends LitElement {
  private devtools?: TanStackDevtoolsCore
  private target?: HTMLDivElement
  override createRenderRoot() {
    return this
  }
  override connectedCallback() {
    super.connectedCallback()

    if (!import.meta.env.DEV) return
    this.target = document.createElement('div')
    document.body.append(this.target)
    this.devtools = new TanStackDevtoolsCore({
      plugins: [pacerDevtoolsPlugin()],
    })
    this.devtools.mount(this.target)
  }
  override disconnectedCallback() {
    this.devtools?.unmount()
    this.target?.remove()
    this.devtools = undefined
    this.target = undefined

    super.disconnectedCallback()
  }
  override render() {
    return html`<div>
      <pacer-counter></pacer-counter>
      <hr />
      <pacer-search></pacer-search>
      <hr />
      <pacer-range></pacer-range>
    </div>`
  }
}
customElements.define('pacer-example', Example)
document.getElementById('app')!.append(document.createElement('pacer-example'))

// examples/octane/useDebouncedValue/src/main.tsx
import { useState } from 'octane'
import { createRoot } from 'octane'
import { useDebouncedValue } from '@tanstack/octane-pacer/debouncer'

function App1() {
  const [instantCount, setInstantCount] = useState(0)

  function increment() {
    setInstantCount((c) => c + 1)
  }

  // highest-level hook that watches an instant local state value and returns a debounced value
  const [debouncedCount] = useDebouncedValue(
    instantCount,
    {
      wait: 500,
      // enabled: () => instantCount > 2, // optional, defaults to true
      // leading: true, // optional, defaults to false
    },
    // Alternative to debouncer.Subscribe: pass a selector as 3rd arg to cause re-renders and subscribe to state
    // (state) => state,
  )

  return (
    <div>
      <h1>{'TanStack Pacer useDebouncedValue Example 1'}</h1>
      <table>
        <tbody>
          <tr>
            <td>{'Instant Count:'}</td>
            <td>{instantCount}</td>
          </tr>
          <tr>
            <td>{'Debounced Count:'}</td>
            <td>{debouncedCount}</td>
          </tr>
        </tbody>
      </table>
      <div>
        <button onClick={increment}>{'Increment'}</button>
      </div>
    </div>
  )
}

function App2() {
  const [instantSearch, setInstantSearch] = useState('')

  // highest-level hook that watches an instant local state value and returns a debounced value
  // optionally, grab the debouncer from the last index of the returned array
  const [debouncedSearch] = useDebouncedValue(
    instantSearch,
    {
      wait: 500,
      enabled: instantSearch.length > 2, // optional, defaults to true
    },
    // Alternative to debouncer.Subscribe: pass a selector as 3rd arg to cause re-renders and subscribe to state
    // (state) => state,
  )

  function handleSearchChange(e: Event & { currentTarget: HTMLInputElement }) {
    setInstantSearch(e.currentTarget.value)
  }

  return (
    <div>
      <h1>{'TanStack Pacer useDebouncedValue Example 2'}</h1>
      <div>
        <input
          autoFocus
          type="search"
          value={instantSearch}
          onInput={handleSearchChange}
          placeholder="Type to search..."
          style={{ width: '100%' }}
        />
      </div>
      <table>
        <tbody>
          <tr>
            <td>{'Instant Search:'}</td>
            <td>{instantSearch}</td>
          </tr>
          <tr>
            <td>{'Debounced Search:'}</td>
            <td>{debouncedSearch}</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}

function App3() {
  const [currentValue, setCurrentValue] = useState(50)
  const [submittedCount, setSubmittedCount] = useState(1)

  // highest-level hook that watches an instant local state value and returns a debounced value
  const [debouncedValue, debouncer] = useDebouncedValue(
    currentValue,
    {
      wait: 250,
    },
    // Alternative to debouncer.Subscribe: pass a selector as 3rd arg to cause re-renders and subscribe to state
    // (state) => state,
  )

  function handleRangeChange(e: Event & { currentTarget: HTMLInputElement }) {
    const newValue = parseInt(e.currentTarget.value, 10)
    setCurrentValue(newValue)
    setSubmittedCount((c) => c + 1)
  }

  return (
    <div>
      <h1>{'TanStack Pacer useDebouncedValue Example 3'}</h1>
      <div style={{ marginBottom: '20px' }}>
        <label>
          {'Current Range:'}
          <input
            type="range"
            min="0"
            max="100"
            value={currentValue}
            onInput={handleRangeChange}
            style={{ width: '100%' }}
          />
          <span>{currentValue}</span>
        </label>
      </div>
      <div style={{ marginBottom: '20px' }}>
        <label>
          {'Debounced Range (Readonly):'}
          <input
            type="range"
            min="0"
            max="100"
            value={debouncedValue}
            disabled
            style={{ width: '100%' }}
          />
          <span>{debouncedValue}</span>
        </label>
      </div>
      <debouncer.Subscribe
        selector={(state) => ({
          isPending: state.isPending,
          executionCount: state.executionCount,
        })}
      >
        {({ isPending, executionCount }) => (
          <>
            <table>
              <tbody>
                <tr>
                  <td>{'Is Pending:'}</td>
                  <td>{isPending.toString()}</td>
                </tr>
                <tr>
                  <td>{'Values Submitted:'}</td>
                  <td>{submittedCount}</td>
                </tr>
                <tr>
                  <td>{'Debounced Executions:'}</td>
                  <td>{executionCount}</td>
                </tr>
                <tr>
                  <td>{'Saved Executions:'}</td>
                  <td>{submittedCount - executionCount}</td>
                </tr>
                <tr>
                  <td>{'% Reduction:'}</td>
                  <td>
                    {submittedCount === 0
                      ? '0'
                      : Math.round(
                          ((submittedCount - executionCount) / submittedCount) *
                            100,
                        )}
                    {'%'}
                  </td>
                </tr>
              </tbody>
            </table>
            <div style={{ color: '#666', fontSize: '0.9em' }}>
              <p>{'Debounced to 250ms wait time'}</p>
            </div>
          </>
        )}
      </debouncer.Subscribe>
      <pre style={{ marginTop: '20px' }}>
        <debouncer.Subscribe selector={(state) => state}>
          {(state) => JSON.stringify(state, null, 2)}
        </debouncer.Subscribe>
      </pre>
    </div>
  )
}

function PacerExample() {
  return (
    <div>
      <App1 />
      <hr />
      <App2 />
      <hr />
      <App3 />
    </div>
  )
}
createRoot(document.getElementById('app')!).render(PacerExample)
