// packages/solid-pacer/src/async-queuer/createAsyncQueuer.ts
import { AsyncQueuer } from '@tanstack/pacer/async-queuer'
import { useStore } from '@tanstack/solid-store'
import { createEffect, onCleanup } from 'solid-js'
import { useDefaultPacerOptions } from '../provider/PacerProvider'
import type { Store } from '@tanstack/solid-store'
import type { Accessor, JSX } from 'solid-js'
import type {
  AsyncQueuerOptions,
  AsyncQueuerState,
} from '@tanstack/pacer/async-queuer'

export interface SolidAsyncQueuer<TValue, TSelected = {}> extends Omit<
  AsyncQueuer<TValue>,
  'store'
> {
  /**
   * A Solid component that allows you to subscribe to the queuer state.
   *
   * This is useful for tracking specific parts of the queuer state
   * deep in your component tree without needing to pass a selector to the hook.
   *
   * @example
   * <queuer.Subscribe selector={(state) => ({ pendingItems: state.pendingItems, activeItems: state.activeItems })}>
   *   {(state) => (
   *     <div>Pending: {state().pendingItems.length}, Active: {state().activeItems.length}</div>
   *   )}
   * </queuer.Subscribe>
   */
  Subscribe: <TSelected>(props: {
    selector: (state: AsyncQueuerState<TValue>) => TSelected
    children: ((state: Accessor<TSelected>) => JSX.Element) | JSX.Element
  }) => JSX.Element
  /**
   * Reactive state that will be updated when the queuer state changes
   *
   * Use this instead of `queuer.store.state`
   */
  readonly state: Accessor<Readonly<TSelected>>
  /**
   * @deprecated Use `queuer.state` instead of `queuer.store.state` if you want to read reactive state.
   * The state on the store object is not reactive, as it has not been wrapped in a `useStore` hook internally.
   * Although, you can make the state reactive by using the `useStore` in your own usage.
   */
  readonly store: Store<Readonly<AsyncQueuerState<TValue>>>
}

/**
 * Creates a Solid-compatible AsyncQueuer instance for managing an asynchronous queue of items, exposing Solid signals for all stateful properties.
 *
 * Features:
 * - Priority queueing via `getPriority` or item `priority` property
 * - Configurable concurrency limit
 * - FIFO (First In First Out) or LIFO (Last In First Out) queue behavior
 * - Pause/resume processing
 * - Task cancellation
 * - Item expiration
 * - Lifecycle callbacks for success, error, settled, items change, etc.
 * - All stateful properties (active items, pending items, counts, etc.) are exposed as Solid signals for reactivity
 *
 * Tasks are processed concurrently up to the configured concurrency limit. When a task completes,
 * the next pending task is processed if the concurrency limit allows.
 *
 * Error Handling:
 * - If an `onError` handler is provided, it will be called with the error and queuer instance
 * - If `throwOnError` is true (default when no onError handler is provided), the error will be thrown
 * - If `throwOnError` is false (default when onError handler is provided), the error will be swallowed
 * - Both onError and throwOnError can be used together; the handler will be called before any error is thrown
 * - The error state can be checked using the underlying AsyncQueuer instance
 *
 * ## State Management and Selector
 *
 * The hook uses TanStack Store for reactive state management. You can subscribe to state changes
 * in two ways:
 *
 * **1. Using `queuer.Subscribe` component (Recommended for component tree subscriptions)**
 *
 * Use the `Subscribe` component to subscribe to state changes deep in your component tree without
 * needing to pass a selector to the hook. This is ideal when you want to subscribe to state
 * in child components.
 *
 * **2. Using the `selector` parameter (For hook-level subscriptions)**
 *
 * The `selector` parameter allows you to specify which state changes will trigger reactive updates
 * at the hook level, optimizing performance by preventing unnecessary updates when irrelevant
 * state changes occur.
 *
 * **By default, there will be no reactive state subscriptions** and you must opt-in to state
 * tracking by providing a selector function or using the `Subscribe` component. This prevents unnecessary
 * updates and gives you full control over when your component tracks state changes.
 *
 * Available state properties:
 * - `activeItems`: Array of items currently being processed
 * - `errorCount`: Number of items that failed processing
 * - `isRunning`: Whether the queuer is currently running (not stopped)
 * - `pendingItems`: Array of items waiting to be processed
 * - `rejectionCount`: Number of items that were rejected (expired or failed validation)
 * - `settleCount`: Number of items that have completed processing (successful or failed)
 * - `successCount`: Number of items that were processed successfully
 *
 * ## Unmount behavior
 *
 * By default, the primitive stops the queuer when the owning component unmounts.
 * Use the `onUnmount` option to customize this. For example, to flush pending items instead:
 *
 * ```tsx
 * const queuer = createAsyncQueuer(fn, {
 *   concurrency: 2,
 *   started: false,
 *   onUnmount: (q) => q.flush()
 * });
 * ```
 *
 * Note: For async utils, `flush()` returns a Promise and runs fire-and-forget in the cleanup.
 * If your task function updates Solid signals, those updates may run after the component has
 * unmounted, which can cause unexpected reactive updates. Guard your callbacks accordingly when
 * using onUnmount with flush.
 *
 * Example usage:
 * ```tsx
 * // Default behavior - no reactive state subscriptions
 * const asyncQueuer = createAsyncQueuer(async (item) => {
 *   // process item
 *   return await fetchData(item);
 * }, {
 *   initialItems: [],
 *   concurrency: 2,
 *   maxSize: 100,
 *   started: false,
 *   onSuccess: (result) => {
 *     console.log('Item processed:', result);
 *   },
 *   onError: (error) => {
 *     console.error('Processing failed:', error);
 *   }
 * });
 *
 * // Opt-in to track queue state changes (optimized for UI updates)
 * const asyncQueuer = createAsyncQueuer(
 *   async (item) => await fetchData(item),
 *   { concurrency: 2, started: true },
 *   (state) => ({
 *     pendingItems: state.pendingItems,
 *     activeItems: state.activeItems,
 *     isRunning: state.isRunning
 *   })
 * );
 *
 * // Opt-in to track processing metrics changes (optimized for tracking progress)
 * const asyncQueuer = createAsyncQueuer(
 *   async (item) => await fetchData(item),
 *   { concurrency: 2, started: true },
 *   (state) => ({
 *     successCount: state.successCount,
 *     errorCount: state.errorCount,
 *     settleCount: state.settleCount
 *   })
 * );
 *
 * // Add items to queue
 * asyncQueuer.addItem(newItem);
 *
 * // Start processing
 * asyncQueuer.start();
 *
 * // Access the selected state (will be empty object {} unless selector provided)
 * const { pendingItems, activeItems } = asyncQueuer.state();
 * ```
 */
export function createAsyncQueuer<TValue, TSelected = {}>(
  fn: (value: TValue) => Promise<any>,
  options: AsyncQueuerOptions<TValue> = {},
  selector: (state: AsyncQueuerState<TValue>) => TSelected = () =>
    ({}) as TSelected,
): SolidAsyncQueuer<TValue, TSelected> {
  const mergedOptions = {
    ...useDefaultPacerOptions().asyncQueuer,
    ...options,
  } as AsyncQueuerOptions<TValue>

  const asyncQueuer = new AsyncQueuer<TValue>(
    fn,
    mergedOptions,
  ) as unknown as SolidAsyncQueuer<TValue, TSelected>

  asyncQueuer.Subscribe = function Subscribe<TSelected>(props: {
    selector: (state: AsyncQueuerState<TValue>) => TSelected
    children: ((state: Accessor<TSelected>) => JSX.Element) | JSX.Element
  }) {
    const selected = useStore(asyncQueuer.store, props.selector)

    return typeof props.children === 'function'
      ? props.children(selected)
      : props.children
  }

  const state = useStore(asyncQueuer.store, selector)

  createEffect(() => {
    onCleanup(() => {
      if (mergedOptions.onUnmount) {
        mergedOptions.onUnmount(asyncQueuer as unknown as AsyncQueuer<TValue>)
      } else {
        asyncQueuer.stop()
      }
    })
  })

  return {
    ...asyncQueuer,
    state,
  } as SolidAsyncQueuer<TValue, TSelected> // omit `store` in favor of `state`
}

// packages/lit-pacer/src/async-queuer/createAsyncQueuer.ts
import { AsyncQueuer } from '@tanstack/pacer/async-queuer'
import { bindPacer } from '../utils/bindPacer'
import { useDefaultPacerOptions } from '../provider/PacerProvider'
import type { LitPacerSubscribe } from '../utils/subscribe'
import type {
  AsyncQueuerOptions,
  AsyncQueuerState,
} from '@tanstack/pacer/async-queuer'
import type { ReactiveControllerHost } from 'lit'
import type { LitPacerOptions } from '../types'

/** Options for createAsyncQueuer, including owner cleanup. */
export interface LitAsyncQueuerOptions<
  TValue,
  TSelected = {},
> extends AsyncQueuerOptions<TValue> {
  /** Replaces default cleanup. Use this to flush, cancel, or stop pending work. */
  onUnmount?: (instance: LitAsyncQueuer<TValue, TSelected>) => void
}

/** An AsyncQueuer with framework-reactive selected state. All core methods remain available. */
export interface LitAsyncQueuer<TValue, TSelected = {}> extends Omit<
  AsyncQueuer<TValue>,
  'options' | 'setOptions'
> {
  options: AsyncQueuer<TValue>['options'] &
    LitAsyncQueuerOptions<TValue, TSelected>
  setOptions: (
    options: Partial<LitAsyncQueuerOptions<TValue, TSelected>>,
  ) => void
  /** Subscribes a child owner to selected state with automatic cleanup. */
  subscribe: LitPacerSubscribe<AsyncQueuerState<TValue>>
  /** Selected state. Pass a selector to opt in; the default selection is an empty object. */
  readonly state: Readonly<TSelected>
}

/**
 * Creates and retains the AsyncQueuer for its Lit owner.
 *
 * Retains items until they are processed. Use addItem to enqueue work and start, stop, execute, clear, or flush to control processing. Selected state exposes pending items, capacity, and completed work.
 *
 * The callback may return a Promise. Core result, error, retry, and abort behavior is preserved.
 * Use onSuccess, onError, and onSettled for execution outcomes.
 *
 * ## State and subscriptions
 *
 * Pass a selector to track only the state consumed by the owner. The default selection is {},
 * so utility state changes do not update the owner unless it opts in. Selection uses shallow
 * comparison. The raw store remains available for additional subscriptions.
 * Use utility.subscribe(childHost, selector) for a child subscription. It returns a getter
 * and cleans up with the child without canceling the parent utility.
 *
 * Available state fields:
 *
 * - `activeItems`: Items currently being processed by the queuer
 * - `addItemCount`: Number of times addItem has been called (for reduction calculations)
 * - `errorCount`: Number of task executions that have resulted in errors
 * - `executionCount`: Number of times execute has been called
 * - `expirationCount`: Number of items that have been removed from the queue due to expiration
 * - `isEmpty`: Whether the queuer has no items to process (items array is empty)
 * - `isExecuting`: Whether the queuer is currently executing
 * - `isFull`: Whether the queuer has reached its maximum capacity
 * - `isIdle`: Whether the queuer is not currently processing any items
 * - `isRunning`: Whether the queuer is active and will process items automatically
 * - `items`: Array of items currently waiting to be processed
 * - `itemTimestamps`: Timestamps when items were added to the queue for expiration tracking
 * - `lastResult`: The result from the most recent task execution
 * - `pendingTick`: Whether the queuer has a pending timeout for processing the next item
 * - `rejectionCount`: Number of items that have been rejected from being added to the queue
 * - `settleCount`: Number of task executions that have completed (either successfully or with errors)
 * - `size`: Number of items currently in the queue
 * - `status`: Current processing status - 'idle' when not processing, 'running' when active, 'stopped' when paused
 * - `successCount`: Number of task executions that have completed successfully
 *
 * ## Options and ownership
 *
 * Pass an options object with property getters or a factory. Top-level properties are read
 * reactively; function-valued core options remain callbacks. Local options override provider
 * defaults. Updates retain the utility, its store, counters, and pending work.
 * Disconnecting the host calls stop() and abort().
 * onUnmount replaces default cleanup and receives the same adapter instance. A custom callback
 * must perform all required cleanup. Use flush() where supported to finish pending work.
 * Reconnecting the host refreshes options and restores subscriptions to the same instance.
 *
 * @example
 * ```ts
 * import { createAsyncQueuer } from '@tanstack/lit-pacer'
 *
 * const utility = createAsyncQueuer(
 *   this, async (value: string) => { console.log(value) },
 *   { wait: 100 },
 *   (state) => ({ size: state.size }),
 * )
 * utility.addItem('item')
 * // Selected state: utility.state.size
 * ```
 *
 * @param host - Owner of option updates, subscriptions, and cleanup.
 * @param fn - Function executed by the utility.
 * @param options - Core options or a reactive factory, plus an optional onUnmount callback.
 * @param selector - Selects state that updates the owner. Omit to leave selected state empty.
 * @returns The retained utility instance with selected state and child subscriptions.
 */
export function createAsyncQueuer<TValue, TSelected = {}>(
  host: ReactiveControllerHost,
  fn: (item: TValue) => Promise<any>,
  options: LitPacerOptions<LitAsyncQueuerOptions<TValue, TSelected>> = {},
  selector: (state: AsyncQueuerState<TValue>) => TSelected = () =>
    ({}) as TSelected,
): LitAsyncQueuer<TValue, TSelected> {
  const defaults = useDefaultPacerOptions(host)
  const resolve = (): LitAsyncQueuerOptions<TValue, TSelected> => ({
    ...defaults().asyncQueuer,
    ...(typeof options === 'function' ? options() : options),
  })
  const instance = new AsyncQueuer<TValue>(
    fn,
    resolve(),
  ) as unknown as LitAsyncQueuer<TValue, TSelected>
  return bindPacer(host, instance, resolve, selector, () => {
    if (instance.options.onUnmount) {
      instance.options.onUnmount(instance)
      return
    }
    instance.stop()
    instance.abort()
  })
}
