// packages/react-pacer/src/async-queuer/useAsyncQueuer.ts
import { useRef } from 'react'
import { AsyncQueuer } from '@tanstack/pacer/async-queuer'
import type { AsyncQueuerOptions } from '@tanstack/pacer/async-queuer'

/**
 * A lower-level React hook that creates an `AsyncQueuer` instance for managing an async queue of items.
 *
 * This hook provides a flexible, state-management agnostic way to handle queued async operations.
 * It returns a queuer instance with methods to add items, control queue execution, and monitor queue state.
 *
 * The queue can be configured with:
 * - Maximum concurrent operations
 * - Maximum queue size
 * - Processing function for queue items
 * - Various lifecycle callbacks
 *
 * The hook returns an object containing methods to:
 * - Add/remove items from the queue
 * - Start/stop queue processing
 * - Get queue status and items
 * - Register event handlers
 * - Control execution throttling
 *
 * @example
 * ```tsx
 * // Basic async queuer for API requests
 * const asyncQueuer = useAsyncQueuer({
 *   initialItems: [],
 *   concurrency: 2,
 *   maxSize: 100,
 *   started: false,
 * });
 *
 * // Add items to queue
 * asyncQueuer.addItem(newItem);
 *
 * // Start processing
 * asyncQueuer.start();
 *
 * // Monitor queue state
 * const isPending = !asyncQueuer.isIdle();
 * const itemCount = asyncQueuer.size();
 *
 * // Handle results
 * asyncQueuer.onSuccess((result) => {
 *   console.log('Item processed:', result);
 * });
 *
 * asyncQueuer.onError((error) => {
 *   console.error('Processing failed:', error);
 * });
 * ```
 */
export function useAsyncQueuer<TValue>(options: AsyncQueuerOptions<TValue> = {}) {
  const asyncQueuer = useRef<AsyncQueuer<TValue> | null>(null)

  if (!asyncQueuer.current) {
    asyncQueuer.current = new AsyncQueuer(options)
  }

  const setOptions = asyncQueuer.current.setOptions.bind(
    asyncQueuer.current,
  )
  setOptions(options)

  return {
    addItem: asyncQueuer.current.addItem.bind(asyncQueuer.current),
    clear: asyncQueuer.current.clear.bind(asyncQueuer.current),
    getActiveItems: asyncQueuer.current.getActiveItems.bind(
      asyncQueuer.current,
    ),
    getAllItems: asyncQueuer.current.getAllItems.bind(asyncQueuer.current),
    getExecutionCount: asyncQueuer.current.getExecutionCount.bind(
      asyncQueuer.current,
    ),
    getNextItem: asyncQueuer.current.getNextItem.bind(asyncQueuer.current),
    getPendingItems: asyncQueuer.current.getPendingItems.bind(
      asyncQueuer.current,
    ),
    isEmpty: asyncQueuer.current.isEmpty.bind(asyncQueuer.current),
    isFull: asyncQueuer.current.isFull.bind(asyncQueuer.current),
    isIdle: asyncQueuer.current.isIdle.bind(asyncQueuer.current),
    isRunning: asyncQueuer.current.isRunning.bind(asyncQueuer.current),
    onError: asyncQueuer.current.onError.bind(asyncQueuer.current),
    onSettled: asyncQueuer.current.onSettled.bind(asyncQueuer.current),
    onSuccess: asyncQueuer.current.onSuccess.bind(asyncQueuer.current),
    onUpdate: asyncQueuer.current.onUpdate.bind(asyncQueuer.current),
    peek: asyncQueuer.current.peek.bind(asyncQueuer.current),
    reset: asyncQueuer.current.reset.bind(asyncQueuer.current),
    size: asyncQueuer.current.size.bind(asyncQueuer.current),
    start: asyncQueuer.current.start.bind(asyncQueuer.current),
    stop: asyncQueuer.current.stop.bind(asyncQueuer.current),
    throttle: asyncQueuer.current.throttle.bind(asyncQueuer.current),
    setOptions,
  }
}

// packages/solid-pacer/src/async-queuer/useAsyncQueuer.ts
import { createMemo, createSignal } from 'solid-js'
import { AsyncQueuer } from '@tanstack/pacer/async-queuer'
import type { AsyncQueuerOptions } from '@tanstack/pacer/async-queuer'

/**
 * A lower-level React hook that creates an `AsyncQueuer` instance for managing an async queue of items.
 *
 * This hook provides a flexible, state-management agnostic way to handle queued async operations.
 * It returns a queuer instance with methods to add items, control queue execution, and monitor queue state.
 *
 * The queue can be configured with:
 * - Maximum concurrent operations
 * - Maximum queue size
 * - Processing function for queue items
 * - Various lifecycle callbacks
 *
 * The hook returns an object containing methods to:
 * - Add/remove items from the queue
 * - Start/stop queue processing
 * - Get queue status and items
 * - Register event handlers
 * - Control execution throttling
 *
 * @example
 * ```tsx
 * // Basic async queuer for API requests
 * const asyncQueuer = useAsyncQueuer({
 *   initialItems: [],
 *   concurrency: 2,
 *   maxSize: 100,
 *   started: false,
 * });
 *
 * // Add items to queue
 * asyncQueuer.addItem(newItem);
 *
 * // Start processing
 * asyncQueuer.start();
 *
 * // Monitor queue state
 * const isPending = !asyncQueuer.isIdle();
 * const itemCount = asyncQueuer.size();
 *
 * // Handle results
 * asyncQueuer.onSuccess((result) => {
 *   console.log('Item processed:', result);
 * });
 *
 * asyncQueuer.onError((error) => {
 *   console.error('Processing failed:', error);
 * });
 * ```
 */
export function useAsyncQueuer<TValue>(
  options: AsyncQueuerOptions<TValue> = {},
) {
  const [asyncQueuer] = createSignal(() => new AsyncQueuer<TValue>(options))

  const setOptions = createMemo(() =>
    asyncQueuer()().setOptions.bind(asyncQueuer),
  )

  setOptions()(options)

  return createMemo(
    () =>
      ({
        addItem: asyncQueuer()().addItem.bind(asyncQueuer()),
        clear: asyncQueuer()().clear.bind(asyncQueuer()),
        getActiveItems: asyncQueuer()().getActiveItems.bind(asyncQueuer()),
        getAllItems: asyncQueuer()().getAllItems.bind(asyncQueuer()),
        getExecutionCount:
          asyncQueuer()().getExecutionCount.bind(asyncQueuer()),
        getNextItem: asyncQueuer()().getNextItem.bind(asyncQueuer()),
        getPendingItems: asyncQueuer()().getPendingItems.bind(asyncQueuer()),
        isEmpty: asyncQueuer()().isEmpty.bind(asyncQueuer()),
        isFull: asyncQueuer()().isFull.bind(asyncQueuer()),
        isIdle: asyncQueuer()().isIdle.bind(asyncQueuer()),
        isRunning: asyncQueuer()().isRunning.bind(asyncQueuer()),
        onError: asyncQueuer()().onError.bind(asyncQueuer()),
        onSettled: asyncQueuer()().onSettled.bind(asyncQueuer()),
        onSuccess: asyncQueuer()().onSuccess.bind(asyncQueuer()),
        peek: asyncQueuer()().peek.bind(asyncQueuer()),
        reset: asyncQueuer()().reset.bind(asyncQueuer()),
        size: asyncQueuer()().size.bind(asyncQueuer()),
        start: asyncQueuer()().start.bind(asyncQueuer()),
        stop: asyncQueuer()().stop.bind(asyncQueuer()),
      }) as const,
  )
}
