// packages/angular-pacer/src/rate-limiter/createRateLimitedValue.ts
import { effect } from '@angular/core'
import { createRateLimitedSignal } from './createRateLimitedSignal'
import type { Signal } from '@angular/core';
import type { AngularRateLimiter } from './createRateLimiter'
import type {
  RateLimiterOptions,
  RateLimiterState,
} from '@tanstack/pacer/rate-limiter'

type Setter<T> = (value: T | ((prev: T) => T)) => void

/**
 * An Angular function that creates a rate-limited value that updates at most a certain number of times within a time window.
 * Unlike createRateLimitedSignal, this function automatically tracks changes to the input signal
 * and updates the rate-limited value accordingly.
 *
 * The rate-limited value will update according to the configured rate limit, blocking updates
 * once the limit is reached until the window resets.
 *
 * The function returns a tuple containing:
 * - A Signal that provides the current rate-limited value
 * - The rate limiter instance with control methods
 *
 * ## State Management and Selector
 *
 * The function uses TanStack Store for reactive state management via the underlying rate limiter instance.
 * The `selector` parameter allows you to specify which rate limiter state changes will trigger signal updates,
 * optimizing performance by preventing unnecessary subscriptions when irrelevant state changes occur.
 *
 * **By default, there will be no reactive state subscriptions** and you must opt-in to state
 * tracking by providing a selector function. This prevents unnecessary updates and gives you
 * full control over when your component tracks state changes.
 *
 * @example
 * ```ts
 * // Default behavior - no reactive state subscriptions
 * const value = signal(0);
 * const [rateLimitedValue, rateLimiter] = createRateLimitedValue(value, {
 *   limit: 5,
 *   window: 60000,
 *   windowType: 'sliding'
 * });
 *
 * // rateLimitedValue will update at most 5 times per 60 seconds
 * effect(() => {
 *   updateUI(rateLimitedValue());
 * });
 * ```
 */
export function createRateLimitedValue<TValue, TSelected = {}>(
  value: Signal<TValue>,
  initialOptions: RateLimiterOptions<Setter<TValue>>,
  selector?: (state: RateLimiterState) => TSelected,
): [Signal<TValue>, AngularRateLimiter<Setter<TValue>, TSelected>] {
  const [rateLimitedValue, setRateLimitedValue, rateLimiter] =
    createRateLimitedSignal(value(), initialOptions, selector)

  effect(() => {
    setRateLimitedValue(value())
  })

  return [rateLimitedValue, rateLimiter]
}

// packages/solid-pacer/src/rate-limiter/createRateLimitedValue.ts
import { createEffect } from 'solid-js'
import { createRateLimitedSignal } from './createRateLimitedSignal'
import type { SolidPacerOptions } from '../types'
import type {
  SolidRateLimiter,
  SolidRateLimiterOptions,
} from './createRateLimiter'
import type { Accessor, Setter } from 'solid-js'
import type { RateLimiterState } from '@tanstack/pacer/rate-limiter'

/**
 * A high-level Solid hook that creates a rate-limited version of a value that updates at most a certain number of times within a time window.
 * This hook uses Solid's createSignal internally to manage the rate-limited state.
 *
 * Rate limiting is a simple "hard limit" approach - it allows all updates until the limit is reached, then blocks
 * subsequent updates until the window resets. Unlike throttling or debouncing, it does not attempt to space out
 * or intelligently collapse updates. This can lead to bursts of rapid updates followed by periods of no updates.
 *
 * The rate limiter supports two types of windows:
 * - 'fixed': A strict window that resets after the window period. All updates within the window count
 *   towards the limit, and the window resets completely after the period.
 * - 'sliding': A rolling window that allows updates as old ones expire. This provides a more
 *   consistent rate of updates over time.
 *
 * For smoother update patterns, consider:
 * - createThrottledValue: When you want consistent spacing between updates (e.g. UI changes)
 * - createDebouncedValue: When you want to collapse rapid updates into a single update (e.g. search input)
 *
 * Rate limiting should primarily be used when you need to enforce strict limits, like API rate limits.
 *
 * The hook returns a tuple containing:
 * - An accessor function that provides the rate-limited value
 * - The rate limiter instance with control methods
 *
 * For more direct control over rate limiting behavior without Solid state management,
 * consider using the lower-level createRateLimiter hook instead.
 *
 * ## State Management and Selector
 *
 * The hook uses TanStack Store for reactive state management via the underlying rate limiter instance.
 * The `selector` parameter allows you to specify which rate limiter state changes will trigger reactive updates,
 * optimizing performance by preventing unnecessary subscriptions when irrelevant state changes occur.
 *
 * **By default, there will be no reactive state subscriptions** and you must opt-in to state
 * tracking by providing a selector function. This prevents unnecessary reactive updates and gives you
 * full control over when your component subscribes to state changes. Only when you provide a selector will
 * the reactive system track the selected state values.
 *
 * Available rate limiter state properties:
 * - `executionCount`: Number of function executions that have been completed
 * - `executionTimes`: Array of timestamps when executions occurred for rate limiting calculations
 * - `rejectionCount`: Number of function executions that have been rejected due to rate limiting
 *
 * @example
 * ```tsx
 * // Default behavior - no reactive state subscriptions
 * const [rateLimitedValue, rateLimiter] = createRateLimitedValue(rawValue, {
 *   limit: 5,
 *   window: 60000,
 *   windowType: 'sliding'
 * });
 *
 * // Opt-in to reactive updates when execution count changes (optimized for tracking successful updates)
 * const [rateLimitedValue, rateLimiter] = createRateLimitedValue(
 *   rawValue,
 *   { limit: 5, window: 60000, windowType: 'sliding' },
 *   (state) => ({ executionCount: state.executionCount })
 * );
 *
 * // Opt-in to reactive updates when rejection count changes (optimized for tracking rate limit violations)
 * const [rateLimitedValue, rateLimiter] = createRateLimitedValue(
 *   rawValue,
 *   { limit: 5, window: 60000, windowType: 'sliding' },
 *   (state) => ({ rejectionCount: state.rejectionCount })
 * );
 *
 * // Opt-in to reactive updates when execution times change (optimized for window calculations)
 * const [rateLimitedValue, rateLimiter] = createRateLimitedValue(
 *   rawValue,
 *   { limit: 5, window: 60000, windowType: 'sliding' },
 *   (state) => ({ executionTimes: state.executionTimes })
 * );
 *
 * // With rejection callback and fixed window
 * const [rateLimitedValue, rateLimiter] = createRateLimitedValue(rawValue, {
 *   limit: 3,
 *   window: 5000,
 *   windowType: 'fixed',
 *   onReject: (rateLimiter) => {
 *     console.log(`Update rejected. Try again in ${rateLimiter.getMsUntilNextWindow()}ms`);
 *   }
 * });
 *
 * // Access the selected rate limiter state (will be empty object {} unless selector provided)
 * const { executionCount, rejectionCount } = rateLimiter.state;
 * ```
 */
export function createRateLimitedValue<TValue, TSelected = {}>(
  value: Accessor<TValue>,
  initialOptions: SolidPacerOptions<
    SolidRateLimiterOptions<Setter<TValue>, TSelected>
  >,
  selector?: (state: RateLimiterState) => TSelected,
): [Accessor<TValue>, SolidRateLimiter<Setter<TValue>, TSelected>] {
  const [rateLimitedValue, setRateLimitedValue, rateLimiter] =
    createRateLimitedSignal(value(), initialOptions, selector)

  createEffect(() => {
    setRateLimitedValue(value() as any)
  })

  return [rateLimitedValue, rateLimiter]
}
