// packages/solid-pacer/src/provider/PacerProvider.tsx
import { createContext, useContext } from 'solid-js'
import type { JSX } from 'solid-js'
import type { SolidAsyncBatcherOptions } from '../async-batcher/createAsyncBatcher'
import type { SolidAsyncDebouncerOptions } from '../async-debouncer/createAsyncDebouncer'
import type { SolidAsyncQueuerOptions } from '../async-queuer/createAsyncQueuer'
import type { SolidAsyncRateLimiterOptions } from '../async-rate-limiter/createAsyncRateLimiter'
import type { SolidAsyncThrottlerOptions } from '../async-throttler/createAsyncThrottler'
import type { SolidBatcherOptions } from '../batcher/createBatcher'
import type { SolidDebouncerOptions } from '../debouncer/createDebouncer'
import type { SolidQueuerOptions } from '../queuer/createQueuer'
import type { SolidRateLimiterOptions } from '../rate-limiter/createRateLimiter'
import type { SolidThrottlerOptions } from '../throttler/createThrottler'

export interface PacerProviderOptions {
  asyncBatcher?: Partial<SolidAsyncBatcherOptions<any, any>>
  asyncDebouncer?: Partial<SolidAsyncDebouncerOptions<any, any>>
  asyncQueuer?: Partial<SolidAsyncQueuerOptions<any, any>>
  asyncRateLimiter?: Partial<SolidAsyncRateLimiterOptions<any, any>>
  asyncThrottler?: Partial<SolidAsyncThrottlerOptions<any, any>>
  batcher?: Partial<SolidBatcherOptions<any, any>>
  debouncer?: Partial<SolidDebouncerOptions<any, any>>
  queuer?: Partial<SolidQueuerOptions<any, any>>
  rateLimiter?: Partial<SolidRateLimiterOptions<any, any>>
  throttler?: Partial<SolidThrottlerOptions<any, any>>
}

interface PacerContextValue {
  defaultOptions: PacerProviderOptions
}

const PacerContext = createContext<PacerContextValue | null>(null)

export interface PacerProviderProps {
  children: JSX.Element
  defaultOptions?: PacerProviderOptions
}

const DEFAULT_OPTIONS: PacerProviderOptions = {}

export function PacerProvider(props: PacerProviderProps) {
  const contextValue: PacerContextValue = {
    get defaultOptions() {
      return props.defaultOptions ?? DEFAULT_OPTIONS
    },
  }

  return (
    <PacerContext.Provider value={contextValue}>
      {props.children}
    </PacerContext.Provider>
  )
}

export function usePacerContext() {
  return useContext(PacerContext)
}

export function useDefaultPacerOptions() {
  const context = useContext(PacerContext)
  return context?.defaultOptions ?? {}
}

// packages/lit-pacer/src/provider/PacerProvider.ts
import type { ReactiveControllerHost } from 'lit'
import type { LitPacerOptions } from '../types'
import type { LitAsyncBatcherOptions } from '../async-batcher/createAsyncBatcher'
import type { LitAsyncDebouncerOptions } from '../async-debouncer/createAsyncDebouncer'
import type { LitAsyncQueuerOptions } from '../async-queuer/createAsyncQueuer'
import type { LitAsyncRateLimiterOptions } from '../async-rate-limiter/createAsyncRateLimiter'
import type { LitAsyncThrottlerOptions } from '../async-throttler/createAsyncThrottler'
import type { LitBatcherOptions } from '../batcher/createBatcher'
import type { LitDebouncerOptions } from '../debouncer/createDebouncer'
import type { LitQueuerOptions } from '../queuer/createQueuer'
import type { LitRateLimiterOptions } from '../rate-limiter/createRateLimiter'
import type { LitThrottlerOptions } from '../throttler/createThrottler'

export interface PacerProviderOptions {
  asyncBatcher?: Partial<LitAsyncBatcherOptions<any, any>>
  asyncDebouncer?: Partial<LitAsyncDebouncerOptions<any, any>>
  asyncQueuer?: Partial<LitAsyncQueuerOptions<any, any>>
  asyncRateLimiter?: Partial<LitAsyncRateLimiterOptions<any, any>>
  asyncThrottler?: Partial<LitAsyncThrottlerOptions<any, any>>
  batcher?: Partial<LitBatcherOptions<any, any>>
  debouncer?: Partial<LitDebouncerOptions<any, any>>
  queuer?: Partial<LitQueuerOptions<any, any>>
  rateLimiter?: Partial<LitRateLimiterOptions<any, any>>
  throttler?: Partial<LitThrottlerOptions<any, any>>
}

const defaults = new WeakMap<
  ReactiveControllerHost,
  () => PacerProviderOptions
>()
/** Supplies reactive defaults for utilities owned by this host. Call before constructing utilities. */
export function providePacerOptions(
  host: ReactiveControllerHost,
  options: LitPacerOptions<PacerProviderOptions>,
) {
  defaults.set(host, () =>
    typeof options === 'function' ? options() : options,
  )
}
/** Reads defaults for the host on each update. */
export function useDefaultPacerOptions(
  host: ReactiveControllerHost,
): () => PacerProviderOptions {
  return () => defaults.get(host)?.() ?? {}
}
