// examples/svelte/svelte-query-debounced-prefetch/src/PostDetail.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query'
  import { fetchPost } from './api'

  let { postId }: { postId: number } = $props()
  const post = createQuery(() => ({
    queryKey: ['post', postId],
    queryFn: () => fetchPost(postId),
  }))
</script>

{#if post.isLoading}
  <div>Loading post...</div>
{:else}
  <div>
    <h3>{post.data?.title}</h3>
    <p>{post.data?.body}</p>
  </div>
{/if}

// examples/vue/vue-query-queued-prefetch/src/PostDetail.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { fetchPost } from './api'

const props = defineProps<{ postId: number }>()
const { data: post, isLoading } = useQuery(
  computed(() => ({
    queryKey: ['post', props.postId],
    queryFn: () => fetchPost(props.postId),
  })),
)
</script>

<template>
  <div v-if="isLoading">Loading post...</div>
  <div v-else>
    <h3>{{ post?.title }}</h3>
    <p>{{ post?.body }}</p>
  </div>
</template>
