// examples/lit/lit-query-debounced-prefetch/src/PostDetail.ts
import { LitElement, html } from 'lit'
import { createQueryController } from '@tanstack/lit-query'
import { fetchPost } from './api'

export class PostDetail extends LitElement {
  static properties = { postId: { type: Number } }
  postId = 0
  private post = createQueryController(this, () => ({
    queryKey: ['post', this.postId],
    queryFn: () => fetchPost(this.postId),
    enabled: this.postId > 0,
  }))
  override createRenderRoot() {
    return this
  }
  override render() {
    const post = this.post()
    if (post.isLoading) return html`<div>Loading post...</div>`
    return html`<div>
      <h3>${post.data?.title}</h3>
      <p>${post.data?.body}</p>
    </div>`
  }
}
customElements.define('pacer-post-detail', PostDetail)

// examples/svelte/svelte-query-debounced-prefetch/src/PostDetail.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query'
  import { fetchPost } from './api'

  let { postId }: { postId: number } = $props()
  const post = createQuery(() => ({
    queryKey: ['post', postId],
    queryFn: () => fetchPost(postId),
  }))
</script>

{#if post.isLoading}
  <div>Loading post...</div>
{:else}
  <div>
    <h3>{post.data?.title}</h3>
    <p>{post.data?.body}</p>
  </div>
{/if}
