// examples/svelte/svelte-query-throttled-prefetch/src/PostList.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query'
  import { createThrottledValue } from '@tanstack/svelte-pacer'
  import { fetchPosts, fetchPost, queryClient } from './api'

  let { onSelect }: { onSelect: (id: number) => void } = $props()
  const posts = createQuery(() => ({
    queryKey: ['posts'],
    queryFn: fetchPosts,
  }))
  let currentHoveredPostId = $state<number | null>(null)
  const [scheduledHoveredPostId] = createThrottledValue(
    () => currentHoveredPostId,
    {
      wait: 100,
    },
  )

  // Prefetch when Pacer commits the hovered post id.
  $effect(() => {
    const id = scheduledHoveredPostId()
    if (id)
      void queryClient.ensureQueryData({
        queryKey: ['post', id],
        queryFn: () => fetchPost(id),
      })
  })
</script>

{#if posts.isLoading}
  <div>Loading posts...</div>
{:else}
  <div>
    <h2>Posts</h2>
    <ul style="margin: 0; padding: 0">
      {#each posts.data ?? [] as post (post.id)}
        <li style="margin: 2px 0">
          <a
            href={`#post-${post.id}`}
            onmouseenter={() => (currentHoveredPostId = post.id)}
            onclick={() => onSelect(post.id)}
            style="display: block; padding: 4px; cursor: pointer"
            >{post.title}</a
          >
        </li>
      {/each}
    </ul>
  </div>
{/if}

// examples/lit/lit-query-throttled-prefetch/src/PostList.ts
import { LitElement, html } from 'lit'
import { createQueryController } from '@tanstack/lit-query'
import { createThrottledValue } from '@tanstack/lit-pacer'
import { fetchPosts, fetchPost, queryClient } from './api'

export class PostList extends LitElement {
  static properties = {
    currentHoveredPostId: { state: true },
    onSelect: { attribute: false },
  }
  onSelect: (id: number) => void = () => {}
  currentHoveredPostId: number | null = null
  private posts = createQueryController(this, {
    queryKey: ['posts'],
    queryFn: fetchPosts,
  })
  private scheduled = createThrottledValue(
    this,
    () => this.currentHoveredPostId,
    {
      wait: 100,
    },
  )
  private previousHoveredPostId: number | null = null

  override createRenderRoot() {
    return this
  }

  override updated() {
    // Prefetch when Pacer commits the hovered post id.
    const id = this.scheduled[0]()
    if (id && id !== this.previousHoveredPostId) {
      this.previousHoveredPostId = id
      void queryClient.ensureQueryData({
        queryKey: ['post', id],
        queryFn: () => fetchPost(id),
      })
    }
  }

  override render() {
    const posts = this.posts()
    if (posts.isLoading) return html`<div>Loading posts...</div>`
    return html`<div>
      <h2>Posts</h2>
      <ul style="margin: 0; padding: 0">
        ${posts.data?.map(
          (post) =>
            html`<li style="margin: 2px 0">
              <a
                href=${`#post-${post.id}`}
                @mouseenter=${() => (this.currentHoveredPostId = post.id)}
                @click=${() => this.onSelect(post.id)}
                style="display: block; padding: 4px; cursor: pointer"
                >${post.title}</a
              >
            </li>`,
        )}
      </ul>
    </div>`
  }
}
customElements.define('pacer-post-list', PostList)
