// packages/solid-pacer/src/queuer/createQueuer.ts
import { Queuer } from '@tanstack/pacer/queuer'
import { shallow, useSelector } from '@tanstack/solid-store'
import { createEffect, createRenderEffect, onCleanup, untrack } from 'solid-js'
import { createPacerOptions } from '../utils/createPacerOptions'
import { useDefaultPacerOptions } from '../provider/PacerProvider'
import type { SolidPacerOptions } from '../types'
import type { Store } from '@tanstack/solid-store'
import type { Accessor, JSX } from 'solid-js'
import type { QueuerOptions, QueuerState } from '@tanstack/pacer/queuer'

export interface SolidQueuerOptions<
  TValue,
  TSelected = {},
> extends QueuerOptions<TValue> {
  /**
   * Optional callback invoked when the owning component unmounts. Receives the queuer instance.
   * When provided, replaces the default cleanup (stop); use it to call flush(), flushAsBatch(), stop(), add logging, etc.
   */
  onUnmount?: (queuer: SolidQueuer<TValue, TSelected>) => void
}

export interface SolidQueuer<TValue, TSelected = {}> extends Omit<
  Queuer<TValue>,
  'store'
> {
  /**
   * A Solid component that allows you to subscribe to the queuer state.
   *
   * This is useful for tracking specific parts of the queuer state
   * deep in your component tree without needing to pass a selector to the hook.
   *
   * @example
   * <queuer.Subscribe selector={(state) => ({ size: state.size, isRunning: state.isRunning })}>
   *   {(state) => (
   *     <div>Queue: {state().size} items, {state().isRunning ? 'Processing' : 'Idle'}</div>
   *   )}
   * </queuer.Subscribe>
   */
  Subscribe: <TSelected>(props: {
    selector: (state: QueuerState<TValue>) => TSelected
    children: ((state: Accessor<TSelected>) => JSX.Element) | JSX.Element
  }) => JSX.Element
  /**
   * Reactive state that will be updated when the queuer state changes
   *
   * Use this instead of `queuer.store.state`
   */
  readonly state: Accessor<Readonly<TSelected>>
  /**
   * @deprecated Use `queuer.state` instead of `queuer.store.state` if you want to read reactive state.
   * The state on the store object is not reactive, as it has not been wrapped in a `useSelector` hook internally.
   * Although, you can make the state reactive by using the `useSelector` in your own usage.
   */
  readonly store: Store<Readonly<QueuerState<TValue>>>
}

/**
 * Creates a Solid-compatible Queuer instance for managing a synchronous queue of items, exposing Solid signals for all stateful properties.
 *
 * Features:
 * - Synchronous processing of items using the provided `fn` function
 * - FIFO (First In First Out) or LIFO (Last In First Out) queue behavior
 * - Priority queueing via `getPriority` or item `priority` property
 * - Item expiration and removal of stale items
 * - Configurable wait time between processing items
 * - Pause/resume processing
 * - Callbacks for queue state changes, execution, rejection, and expiration
 * - All stateful properties (items, counts, etc.) are exposed as Solid signals for reactivity
 *
 * The queue processes items synchronously in order, with optional delays between each item. When started, it will process one item per tick, with an optional wait time between ticks. You can pause and resume processing with `stop()` and `start()`.
 *
 * By default, the queue uses FIFO behavior, but you can configure LIFO or double-ended queueing by specifying the position when adding or removing items.
 *
 * ## State Management and Selector
 *
 * The hook uses TanStack Store for reactive state management. You can subscribe to state changes
 * in two ways:
 *
 * **1. Using `queuer.Subscribe` component (Recommended for component tree subscriptions)**
 *
 * Use the `Subscribe` component to subscribe to state changes deep in your component tree without
 * needing to pass a selector to the hook. This is ideal when you want to subscribe to state
 * in child components.
 *
 * **2. Using the `selector` parameter (For hook-level subscriptions)**
 *
 * The `selector` parameter allows you to specify which state changes will trigger reactive updates
 * at the hook level, optimizing performance by preventing unnecessary updates when irrelevant
 * state changes occur.
 *
 * **By default, there will be no reactive state subscriptions** and you must opt-in to state
 * tracking by providing a selector function or using the `Subscribe` component. This prevents unnecessary
 * updates and gives you full control over when your component tracks state changes.
 *
 * Available state properties:
 * - `executionCount`: Number of items that have been processed
 * - `isRunning`: Whether the queuer is currently running (not stopped)
 * - `items`: Array of items currently queued for processing
 * - `rejectionCount`: Number of items that were rejected (expired or failed validation)
 *
 * ## Unmount behavior
 *
 * By default, the primitive stops the queuer when the owning component unmounts.
 * Use the `onUnmount` option to customize this. For example, to flush pending items instead:
 *
 * ```tsx
 * const queue = createQueuer(fn, {
 *   started: true,
 *   wait: 1000,
 *   onUnmount: (q) => q.flush()
 * });
 * ```
 *
 * Example usage:
 * ```tsx
 * // Default behavior - no reactive state subscriptions
 * const queue = createQueuer(
 *   (item) => {
 *     // process item synchronously
 *     console.log('Processing', item);
 *   },
 *   {
 *     started: true, // Start processing immediately
 *     wait: 1000,    // Process one item every second
 *     getPriority: (item) => item.priority // Process higher priority items first
 *   }
 * );
 *
 * // Opt-in to track items or isRunning changes (optimized for UI updates)
 * const queue = createQueuer(
 *   (item) => console.log('Processing', item),
 *   { started: true, wait: 1000 },
 *   (state) => ({ items: state.items, isRunning: state.isRunning })
 * );
 *
 * // Opt-in to track execution metrics changes (optimized for tracking progress)
 * const queue = createQueuer(
 *   (item) => console.log('Processing', item),
 *   { started: true, wait: 1000 },
 *   (state) => ({
 *     executionCount: state.executionCount,
 *     rejectionCount: state.rejectionCount
 *   })
 * );
 *
 * // Add items to process - they'll be handled automatically
 * queue.addItem('task1');
 * queue.addItem('task2');
 *
 * // Control the scheduler
 * queue.stop();  // Pause processing
 * queue.start(); // Resume processing
 *
 * // Access the selected state (will be empty object {} unless selector provided)
 * const { items, isRunning } = queue.state();
 * ```
 */
export function createQueuer<TValue, TSelected = {}>(
  fn: (item: TValue) => void,
  options: SolidPacerOptions<SolidQueuerOptions<TValue, TSelected>> = {},
  selector: (state: QueuerState<TValue>) => TSelected = () => ({}) as TSelected,
): SolidQueuer<TValue, TSelected> {
  const mergedOptions = createPacerOptions<
    SolidQueuerOptions<TValue, TSelected>
  >(options, useDefaultPacerOptions().queuer)
  const queuer = new Queuer(fn, mergedOptions()) as unknown as SolidQueuer<
    TValue,
    TSelected
  >

  if (typeof options === 'function') {
    createRenderEffect(() => {
      const latest = mergedOptions()
      untrack(() => queuer.setOptions(latest))
    })
  }

  queuer.Subscribe = function Subscribe<TSelected>(props: {
    selector: (state: QueuerState<TValue>) => TSelected
    children: ((state: Accessor<TSelected>) => JSX.Element) | JSX.Element
  }) {
    const selected = useSelector(queuer.store, props.selector, {
      compare: shallow,
    })

    return typeof props.children === 'function'
      ? props.children(selected)
      : props.children
  }

  const state = useSelector(queuer.store, selector, { compare: shallow })

  createEffect(() => {
    onCleanup(() => {
      const onUnmount = mergedOptions().onUnmount
      if (onUnmount) {
        onUnmount(queuer)
      } else {
        queuer.stop()
      }
    })
  })

  return {
    ...queuer,
    get options() {
      return queuer.options
    },
    set options(value) {
      queuer.options = value
    },
    state,
  } as SolidQueuer<TValue, TSelected> // omit `store` in favor of `state`
}

// packages/lit-pacer/src/queuer/createQueuer.ts
import { Queuer } from '@tanstack/pacer/queuer'
import { bindPacer } from '../utils/bindPacer'
import { useDefaultPacerOptions } from '../provider/PacerProvider'
import type { LitPacerSubscribe } from '../utils/subscribe'
import type { QueuerOptions, QueuerState } from '@tanstack/pacer/queuer'
import type { ReactiveControllerHost } from 'lit'
import type { LitPacerOptions } from '../types'

/** Options for createQueuer, including owner cleanup. */
export interface LitQueuerOptions<
  TValue,
  TSelected = {},
> extends QueuerOptions<TValue> {
  /** Replaces default cleanup. Use this to flush, cancel, or stop pending work. */
  onUnmount?: (instance: LitQueuer<TValue, TSelected>) => void
}

/** A Queuer with framework-reactive selected state. All core methods remain available. */
export interface LitQueuer<TValue, TSelected = {}> extends Omit<
  Queuer<TValue>,
  'options' | 'setOptions'
> {
  options: Queuer<TValue>['options'] & LitQueuerOptions<TValue, TSelected>
  setOptions: (options: Partial<LitQueuerOptions<TValue, TSelected>>) => void
  /** Subscribes a child owner to selected state with automatic cleanup. */
  subscribe: LitPacerSubscribe<QueuerState<TValue>>
  /** Selected state. Pass a selector to opt in; the default selection is an empty object. */
  readonly state: Readonly<TSelected>
}

/**
 * Creates and retains the Queuer for its Lit owner.
 *
 * Retains items until they are processed. Use addItem to enqueue work and start, stop, execute, clear, or flush to control processing. Selected state exposes pending items, capacity, and completed work.
 *
 * ## State and subscriptions
 *
 * Pass a selector to track only the state consumed by the owner. The default selection is {},
 * so utility state changes do not update the owner unless it opts in. Selection uses shallow
 * comparison. The raw store remains available for additional subscriptions.
 * Use utility.subscribe(childHost, selector) for a child subscription. It returns a getter
 * and cleans up with the child without canceling the parent utility.
 *
 * Available state fields:
 *
 * - `addItemCount`: Number of times addItem has been called (for reduction calculations)
 * - `executionCount`: Number of items that have been processed by the queuer
 * - `expirationCount`: Number of items that have been removed from the queue due to expiration
 * - `isEmpty`: Whether the queuer has no items to process (items array is empty)
 * - `isFull`: Whether the queuer has reached its maximum capacity
 * - `isIdle`: Whether the queuer is not currently processing any items
 * - `isRunning`: Whether the queuer is active and will process items automatically
 * - `items`: Array of items currently waiting to be processed
 * - `itemTimestamps`: Timestamps when items were added to the queue for expiration tracking
 * - `pendingTick`: Whether the queuer has a pending timeout for processing the next item
 * - `rejectionCount`: Number of items that have been rejected from being added to the queue
 * - `size`: Number of items currently in the queue
 * - `status`: Current processing status - 'idle' when not processing, 'running' when active, 'stopped' when paused
 *
 * ## Options and ownership
 *
 * Pass an options object with property getters or a factory. Top-level properties are read
 * reactively; function-valued core options remain callbacks. Local options override provider
 * defaults. Updates retain the utility, its store, counters, and pending work.
 * Disconnecting the host calls stop().
 * onUnmount replaces default cleanup and receives the same adapter instance. A custom callback
 * must perform all required cleanup. Use flush() where supported to finish pending work.
 * Reconnecting the host refreshes options and restores subscriptions to the same instance.
 *
 * @example
 * ```ts
 * import { createQueuer } from '@tanstack/lit-pacer'
 *
 * const utility = createQueuer(
 *   this, (value: string) => { console.log(value) },
 *   { wait: 100 },
 *   (state) => ({ size: state.size }),
 * )
 * utility.addItem('item')
 * // Selected state: utility.state.size
 * ```
 *
 * @param host - Owner of option updates, subscriptions, and cleanup.
 * @param fn - Function executed by the utility.
 * @param options - Core options or a reactive factory, plus an optional onUnmount callback.
 * @param selector - Selects state that updates the owner. Omit to leave selected state empty.
 * @returns The retained utility instance with selected state and child subscriptions.
 */
export function createQueuer<TValue, TSelected = {}>(
  host: ReactiveControllerHost,
  fn: (item: TValue) => void,
  options: LitPacerOptions<LitQueuerOptions<TValue, TSelected>> = {},
  selector: (state: QueuerState<TValue>) => TSelected = () => ({}) as TSelected,
): LitQueuer<TValue, TSelected> {
  const defaults = useDefaultPacerOptions(host)
  const resolve = (): LitQueuerOptions<TValue, TSelected> => ({
    ...defaults().queuer,
    ...(typeof options === 'function' ? options() : options),
  })
  const instance = new Queuer<TValue>(fn, resolve()) as unknown as LitQueuer<
    TValue,
    TSelected
  >
  return bindPacer(host, instance, resolve, selector, () => {
    if (instance.options.onUnmount) {
      instance.options.onUnmount(instance)
      return
    }
    instance.stop()
  })
}
