// packages/solid-pacer/src/throttler/createThrottledValue.ts
import { createEffect } from 'solid-js'
import { createThrottledSignal } from './createThrottledSignal'
import type { SolidThrottler } from './createThrottler'
import type { Accessor, Setter } from 'solid-js'
import type {
  ThrottlerOptions,
  ThrottlerState,
} from '@tanstack/pacer/throttler'

/**
 * A high-level Solid hook that creates a throttled version of a value that updates at most once within a specified time window.
 * This hook uses Solid's createSignal internally to manage the throttled state.
 *
 * Throttling ensures the value updates occur at a controlled rate regardless of how frequently the input value changes.
 * This is useful for rate-limiting expensive updates or API calls that depend on rapidly changing values.
 *
 * The hook returns a tuple containing:
 * - An accessor function that provides the throttled value
 * - The throttler instance with control methods
 *
 * The throttled value will update according to the leading/trailing edge behavior specified in the options.
 *
 * For more direct control over throttling behavior without Solid state management,
 * consider using the lower-level createThrottler hook instead.
 *
 * ## State Management and Selector
 *
 * The hook uses TanStack Store for reactive state management via the underlying throttler instance.
 * The `selector` parameter allows you to specify which throttler state changes will trigger reactive updates,
 * optimizing performance by preventing unnecessary subscriptions when irrelevant state changes occur.
 *
 * **By default, there will be no reactive state subscriptions** and you must opt-in to state
 * tracking by providing a selector function. This prevents unnecessary reactive updates and gives you
 * full control over when your component subscribes to state changes. Only when you provide a selector will
 * the reactive system track the selected state values.
 *
 * Available throttler state properties:
 * - `canLeadingExecute`: Whether the throttler can execute on the leading edge
 * - `canTrailingExecute`: Whether the throttler can execute on the trailing edge
 * - `executionCount`: Number of function executions that have been completed
 * - `isPending`: Whether the throttler is waiting for the timeout to trigger trailing execution
 * - `lastArgs`: The arguments from the most recent call to maybeExecute
 * - `lastExecutionTime`: Unix timestamp of the last execution
 * - `nextExecutionTime`: Unix timestamp of the next allowed execution
 * - `status`: Current execution status ('disabled' | 'idle' | 'pending')
 *
 * @example
 * ```tsx
 * // Default behavior - no reactive state subscriptions
 * const [throttledValue, throttler] = createThrottledValue(rawValue, { wait: 1000 });
 *
 * // Opt-in to reactive updates when pending state changes (optimized for loading indicators)
 * const [throttledValue, throttler] = createThrottledValue(
 *   rawValue,
 *   { wait: 1000 },
 *   (state) => ({ isPending: state.isPending })
 * );
 *
 * // Use the throttled value
 * console.log(throttledValue()); // Access the current throttled value
 *
 * // Access throttler state via signals
 * console.log('Is pending:', throttler.state().isPending);
 *
 * // Control the throttler
 * throttler.cancel(); // Cancel any pending updates
 * ```
 */
export function createThrottledValue<TValue, TSelected = {}>(
  value: Accessor<TValue>,
  initialOptions: ThrottlerOptions<Setter<TValue>>,
  selector?: (state: ThrottlerState<Setter<TValue>>) => TSelected,
): [Accessor<TValue>, SolidThrottler<Setter<TValue>, TSelected>] {
  const [throttledValue, setThrottledValue, throttler] = createThrottledSignal(
    value(),
    initialOptions,
    selector,
  )

  createEffect(() => {
    setThrottledValue(value() as any)
  })

  return [throttledValue, throttler]
}

// packages/angular-pacer/src/throttler/createThrottledValue.ts
import { effect } from '@angular/core'
import { createThrottledSignal } from './createThrottledSignal'
import type { Signal } from '@angular/core';
import type { AngularThrottler } from './createThrottler'
import type {
  ThrottlerOptions,
  ThrottlerState,
} from '@tanstack/pacer/throttler'

type Setter<T> = (value: T | ((prev: T) => T)) => void

/**
 * An Angular function that creates a throttled value that updates at most once within a specified time window.
 * Unlike createThrottledSignal, this function automatically tracks changes to the input signal
 * and updates the throttled value accordingly.
 *
 * The throttled value will update at most once within the specified wait time, regardless of
 * how frequently the input value changes.
 *
 * This is useful for deriving throttled values from signals that change frequently,
 * like scroll positions or mouse coordinates, where you want to limit how often downstream effects
 * or calculations occur.
 *
 * The function returns a tuple containing:
 * - A Signal that provides the current throttled value
 * - The throttler instance with control methods
 *
 * ## State Management and Selector
 *
 * The function uses TanStack Store for reactive state management via the underlying throttler instance.
 * The `selector` parameter allows you to specify which throttler state changes will trigger signal updates,
 * optimizing performance by preventing unnecessary subscriptions when irrelevant state changes occur.
 *
 * **By default, there will be no reactive state subscriptions** and you must opt-in to state
 * tracking by providing a selector function. This prevents unnecessary updates and gives you
 * full control over when your component tracks state changes.
 *
 * Available throttler state properties:
 * - `canLeadingExecute`: Whether the throttler can execute on the leading edge
 * - `canTrailingExecute`: Whether the throttler can execute on the trailing edge
 * - `executionCount`: Number of function executions that have been completed
 * - `isPending`: Whether the throttler is waiting for the timeout to trigger execution
 * - `lastArgs`: The arguments from the most recent call to maybeExecute
 * - `lastExecutionTime`: Timestamp of the last execution
 * - `nextExecutionTime`: Timestamp of the next allowed execution
 * - `status`: Current execution status ('disabled' | 'idle' | 'pending')
 *
 * @example
 * ```ts
 * // Default behavior - no reactive state subscriptions
 * const scrollY = signal(0);
 * const [throttledScrollY, throttler] = createThrottledValue(scrollY, {
 *   wait: 100 // Update at most once per 100ms
 * });
 *
 * // Opt-in to reactive updates when pending state changes
 * const [throttledScrollY, throttler] = createThrottledValue(
 *   scrollY,
 *   { wait: 100 },
 *   (state) => ({ isPending: state.isPending })
 * );
 *
 * // throttledScrollY will update at most once per 100ms
 * effect(() => {
 *   updateUI(throttledScrollY());
 * });
 *
 * // Access throttler state via signals
 * console.log('Is pending:', throttler.state().isPending);
 *
 * // Control the throttler
 * throttler.cancel(); // Cancel any pending updates
 * ```
 */
export function createThrottledValue<TValue, TSelected = {}>(
  value: Signal<TValue>,
  initialOptions: ThrottlerOptions<Setter<TValue>>,
  selector?: (state: ThrottlerState<Setter<TValue>>) => TSelected,
): [Signal<TValue>, AngularThrottler<Setter<TValue>, TSelected>] {
  const [throttledValue, setThrottledValue, throttler] = createThrottledSignal(
    value(),
    initialOptions,
    selector,
  )

  effect(() => {
    setThrottledValue(value())
  })

  return [throttledValue, throttler]
}
