// examples/svelte/throttled-callback/src/Search.svelte
<script lang="ts">
  import { createThrottler } from '@tanstack/svelte-pacer/throttler'

  let searchText = $state('')

  let searchTextRef = $state('')

  let throttledSearchText = $state('')

  const throttledSetSearch = createThrottler(
    (value: typeof throttledSearchText) => {
      throttledSearchText = value
    },
    () => ({
      wait: 1000,
      enabled: () => searchTextRef.length > 2,
    }),
  ).maybeExecute

  function handleSearchChange(e: Event) {
    const newValue = (e.target as HTMLInputElement).value
    searchTextRef = newValue
    searchText = newValue
    throttledSetSearch(newValue)
  }
</script>

<div>
  <h1>TanStack Pacer createThrottler Example 2</h1>
  <div>
    <input
      type="search"
      value={searchText}
      oninput={handleSearchChange}
      placeholder="Type to search..."
      style="width: 100%"
    />
  </div>
  <table>
    <tbody
      ><tr><td>Instant Search:</td><td>{searchText}</td></tr><tr
        ><td>Throttled Search:</td><td>{throttledSearchText}</td></tr
      ></tbody
    >
  </table>
</div>

// examples/vue/useThrottler/src/Search.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useThrottler } from '@tanstack/vue-pacer/throttler'

const instantSearch = ref('')

const throttledSearch = ref('')

const setSearchThrottler = useThrottler(
  (value: typeof throttledSearch.value) => {
    throttledSearch.value = value
  },
  () => ({
    key: 'search',
    wait: 1000,
    enabled: () => instantSearch.value.length > 2,
  }),
)

function handleSearchChange(e: Event) {
  const newValue = (e.target as HTMLInputElement).value
  instantSearch.value = newValue
  setSearchThrottler.maybeExecute(newValue)
}
</script>
<template>
  <div>
    <h1>TanStack Pacer useThrottler Example 2</h1>
    <div>
      <input
        autofocus
        type="search"
        :value="instantSearch"
        @input="handleSearchChange"
        placeholder="Type to search..."
        :style="{ width: '100%' }"
      />
    </div>
    <table>
      <tbody>
        <setSearchThrottler.Subscribe
          :selector="(state) => ({ executionCount: state.executionCount })"
          v-slot="{ executionCount }"
          ><tr>
            <td>Execution Count:</td>
            <td>{{ executionCount }}</td>
          </tr>
          <tr>
            <td>Instant Search:</td>
            <td>{{ instantSearch }}</td>
          </tr>
          <tr>
            <td>Throttled Search:</td>
            <td>{{ throttledSearch }}</td>
          </tr></setSearchThrottler.Subscribe
        >
      </tbody>
    </table>
    <div><button @click="() => setSearchThrottler.flush()">Flush</button></div>
    <setSearchThrottler.Subscribe :selector="(state) => state" v-slot="state">
      <pre :style="{ marginTop: '20px' }">{{
        JSON.stringify(state, null, 2)
      }}</pre>
    </setSearchThrottler.Subscribe>
  </div>
</template>
