// examples/svelte/debounce/src/Search.svelte
<script lang="ts">
  import { debounce } from '@tanstack/svelte-pacer/debouncer'

  let searchText = $state('')

  let debouncedSearchText = $state('')

  // Create debounced setter function - Stable reference required!
  const debouncedSetSearch = debounce(
    (value: typeof debouncedSearchText) => (debouncedSearchText = value),
    {
      wait: 500,
    },
  )

  function handleSearchChange(e: Event) {
    const newValue = (e.target as HTMLInputElement).value
    searchText = newValue
    debouncedSetSearch(newValue)
  }
</script>

<div>
  <h1>TanStack Pacer debounce Example 2</h1>
  <div>
    <input
      type="search"
      value={searchText}
      oninput={handleSearchChange}
      placeholder="Type to search..."
      style="width: 100%"
    />
  </div>
  <table>
    <tbody
      ><tr><td>Instant Search:</td><td>{searchText}</td></tr><tr
        ><td>Debounced Search:</td><td>{debouncedSearchText}</td></tr
      ></tbody
    >
  </table>
</div>

// examples/vue/throttle/src/Search.vue
<script setup lang="ts">
import { ref } from 'vue'
import { throttle } from '@tanstack/vue-pacer/throttler'

const text = ref('')

const throttledText = ref('')

// Create throttled setter function - Stable reference required!
const throttledSetText = throttle(
  (value: typeof throttledText.value) => (throttledText.value = value),
  {
    wait: 1000,
  },
)

function handleTextChange(e: Event) {
  const newValue = (e.target as HTMLInputElement).value
  text.value = newValue
  throttledSetText(newValue)
}
</script>
<template>
  <div>
    <h1>TanStack Pacer throttle Example 2</h1>
    <div>
      <input
        type="search"
        :value="text"
        @input="handleTextChange"
        placeholder="Type text (throttled to 1 update per second)..."
        :style="{ width: '100%' }"
      />
    </div>
    <table>
      <tbody>
        <tr>
          <td>Instant Text:</td>
          <td>{{ text }}</td>
        </tr>
        <tr>
          <td>Throttled Text:</td>
          <td>{{ throttledText }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
