// packages/pacer-solid-devtools/src/devtools.tsx
import { PacerDevtoolsCore } from '@tanstack/pacer-devtools'
import { createSignal, onCleanup, onMount } from 'solid-js'

interface PacerDevtoolsSolidInit {}

export const PacerDevtoolsPanel = (_props?: PacerDevtoolsSolidInit) => {
  let devToolRef: HTMLDivElement | undefined
  const [devtools] = createSignal(new PacerDevtoolsCore({}))
  onMount(() => {
    if (devToolRef) {
      devtools().mount(devToolRef)

      onCleanup(() => {
        devtools().unmount()
      })
    }
  })

  return <div style={{ height: '100%' }} ref={devToolRef} />
}

// packages/pacer-react-devtools/src/devtools.tsx
import React, { useEffect, useRef, useState } from 'react'
import { PacerDevtoolsCore } from '@tanstack/pacer-devtools'

interface PacerDevtoolsReactInit {}

export const PacerDevtoolsPanel = (_props?: PacerDevtoolsReactInit) => {
  const devToolRef = useRef<HTMLDivElement>(null)

  const [devtools] = useState(() => new PacerDevtoolsCore({}))
  useEffect(() => {
    if (devToolRef.current) {
      devtools.mount(devToolRef.current)
    }

    return () => devtools.unmount()
  }, [devtools])

  return <div style={{ height: '100%' }} ref={devToolRef} />
}
