// examples/svelte/async-debounced-callback/src/App.svelte
<script lang="ts">
  import { TanStackDevtools } from '@tanstack/svelte-devtools'
  import { pacerDevtoolsPlugin } from '@tanstack/svelte-pacer-devtools'
  import { createAsyncDebouncer } from '@tanstack/svelte-pacer/async-debouncer'

  interface SearchResult {
    id: number
    title: string
  }
  // Simulate API call with fake data
  const fakeApi = async (term: string): Promise<Array<SearchResult>> => {
    await new Promise((resolve) => setTimeout(resolve, 500)) // Simulate network delay
    if (term === 'error') {
      throw new Error('Simulated API error')
    }
    return [
      { id: 1, title: `${term} result ${Math.floor(Math.random() * 100)}` },
      { id: 2, title: `${term} result ${Math.floor(Math.random() * 100)}` },
      { id: 3, title: `${term} result ${Math.floor(Math.random() * 100)}` },
    ]
  }
  let searchTerm = $state('')

  let results = $state<Array<SearchResult>>([])

  let isLoading = $state(false)

  let error = $state<string | null>(null)

  const debouncedSearch = createAsyncDebouncer(
    async (term: string) => {
      if (!term.trim()) {
        results = []
        return []
      }
      isLoading = true
      error = null
      try {
        const data = await fakeApi(term)
        results = data
        return data
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : 'Unknown error'
        error = errorMessage
        results = []
        throw err
      } finally {
        isLoading = false
      }
    },
    () => ({
      wait: 500,
      // leading: true, // optional, defaults to false
      // trailing: true, // optional, defaults to true
    }),
  ).maybeExecute

  async function handleSearchChange(e: Event) {
    const newValue = (e.target as HTMLInputElement).value
    searchTerm = newValue
    try {
      await debouncedSearch(newValue)
    } catch (err) {
      // Error is already handled in the debounced function
      console.log('Search failed:', err)
    }
  }

  let email = $state('')

  let validationResult = $state<{
    isValid: boolean
    message: string
  } | null>(null)

  let isValidating = $state(false)

  // Simulate email validation API
  const validateEmail = async (
    emailAddress: string,
  ): Promise<{
    isValid: boolean
    message: string
  }> => {
    await new Promise((resolve) => setTimeout(resolve, 400))
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    const isValid = emailRegex.test(emailAddress)
    return {
      isValid,
      message: isValid
        ? 'Email is valid!'
        : 'Please enter a valid email address',
    }
  }

  const debouncedValidateEmail = createAsyncDebouncer(
    async (emailAddress: string) => {
      if (!emailAddress.trim()) {
        validationResult = null
        return null
      }
      isValidating = true
      try {
        const result = await validateEmail(emailAddress)
        validationResult = result
        return result
      } finally {
        isValidating = false
      }
    },
    () => ({
      wait: 750,
      leading: false,
    }),
  ).maybeExecute

  function handleEmailChange(e: Event) {
    const newEmail = (e.target as HTMLInputElement).value
    email = newEmail
    debouncedValidateEmail(newEmail)
  }

  let count = $state(0)

  let apiCallCount = $state(0)

  // Simulate API call that returns a value
  const incrementApi = async (value: number): Promise<number> => {
    await new Promise((resolve) => setTimeout(resolve, 300))
    const newCount = value + 1
    apiCallCount = apiCallCount + 1
    return newCount
  }

  const debouncedIncrement = createAsyncDebouncer(
    async (currentValue: number) => {
      const result = await incrementApi(currentValue)
      count = result
      return result
    },
    () => ({
      wait: 1000,
      leading: false, // Don't execute immediately
      trailing: true, // Execute after delay
    }),
  ).maybeExecute

  function handleIncrement() {
    // Update local state immediately for instant feedback
    const newCount = count + 1
    count = newCount
    // Debounced API call
    debouncedIncrement(newCount)
  }
</script>

<div>
  <div>
    <h1>TanStack Pacer createAsyncDebouncer Example 1</h1>
    <div>
      <input
        type="search"
        value={searchTerm}
        oninput={handleSearchChange}
        placeholder="Type to search... (try 'error' to see error handling)"
        style="width: 100%; margin-bottom: 10px"
      />
    </div>
    {#if isLoading}<p style="color: blue">Searching...</p>{/if}{#if error}<p
        style="color: red"
      >
        Error: {error}
      </p>{/if}
    <div>
      <p>Current search term: {searchTerm}</p>
      {#if results.length > 0}<div>
          <h3>Results:</h3>
          <ul>
            {#each results as result, index (index)}<li>
                {result.title}
              </li>{/each}
          </ul>
        </div>{/if}
    </div>
  </div>
  <hr />
  <div>
    <h1>TanStack Pacer createAsyncDebouncer Example 2</h1>
    <table>
      <tbody
        ><tr><td>Current Count:</td><td>{count}</td></tr><tr
          ><td>API Calls Made:</td><td>{apiCallCount}</td></tr
        ></tbody
      >
    </table>
    <div>
      <button onclick={handleIncrement}>Increment (debounced API call)</button>
    </div>
    <p style="font-size: 0.9em; color: #666">
      Click rapidly - API calls are debounced to 1 second, but UI updates
      immediately
    </p>
  </div>
  <hr />
  <div>
    <h1>TanStack Pacer createAsyncDebouncer Example 3</h1>
    <div style="margin-bottom: 20px">
      <label
        >Email Address:<input
          type="email"
          value={email}
          oninput={handleEmailChange}
          placeholder="Enter your email..."
          style={`width: 100%; margin-top: 5px; padding: 8px; border-color: ${
            validationResult?.isValid === false
              ? 'red'
              : validationResult?.isValid === true
                ? 'green'
                : 'initial'
          }`}
        /></label
      >
    </div>
    {#if isValidating}<p style="color: blue">
        Validating email...
      </p>{/if}{#if validationResult}<p
        style={`color: ${validationResult.isValid ? 'green' : 'red'}; font-weight: bold`}
      >
        {validationResult.message}
      </p>{/if}
    <p style="font-size: 0.9em; color: #666">
      Email validation is debounced to 750ms after you stop typing
    </p>
  </div>
</div>
{#if import.meta.env.DEV}<TanStackDevtools
    plugins={[pacerDevtoolsPlugin()]}
  />{/if}

// examples/vue/useAsyncThrottler/src/App.vue
<script setup lang="ts">
import { TanStackDevtools } from '@tanstack/vue-devtools'
import { pacerDevtoolsPlugin } from '@tanstack/vue-pacer-devtools'
import { ref } from 'vue'
import { useAsyncThrottler } from '@tanstack/vue-pacer/async-throttler'

const dev = import.meta.env.DEV
const plugins = [pacerDevtoolsPlugin()]

interface SearchResult {
  id: number
  title: string
}
// Simulate API call with fake data
const fakeApi = async (term: string): Promise<Array<SearchResult>> => {
  await new Promise((resolve) => setTimeout(resolve, 500)) // Simulate network delay
  return [
    { id: 1, title: `${term} result ${Math.floor(Math.random() * 100)}` },
    { id: 2, title: `${term} result ${Math.floor(Math.random() * 100)}` },
    { id: 3, title: `${term} result ${Math.floor(Math.random() * 100)}` },
  ]
}
const searchTerm = ref('')

const results = ref<Array<SearchResult>>([])

const error = ref<Error | null>(null)

// The function that will become throttled
const handleSearch = async (term: string) => {
  if (!term) {
    results.value = []
    return
  }
  // throw new Error('Test error') // you don't have to catch errors here (though you still can). The onError optional handler will catch it
  const data = await fakeApi(term)
  results.value = data
  error.value = null
  return data // this could alternatively be a void function without a return
}

const setSearchAsyncThrottler = useAsyncThrottler(handleSearch, () => ({
  key: 'useAsyncThrottler',
  // leading: true, // default
  // trailing: true, // default
  wait: 1000, // Wait 1 second between API calls
  onError: (cause) => {
    // optional error handler
    console.error('Search failed:', cause)
    error.value = cause as Error
    results.value = []
  },
  // throwOnError: true,
}))

// get and name our throttled function
const handleSearchThrottled = setSearchAsyncThrottler.maybeExecute

// instant event handler that calls both the instant local state setter and the throttled function
async function onSearchChange(e: Event) {
  const newTerm = (e.target as HTMLInputElement).value
  searchTerm.value = newTerm
  const result = await handleSearchThrottled(newTerm) // optionally await if you need to
  console.log('result', result)
}
</script>

<template>
  <div>
    <h1>TanStack Pacer useAsyncThrottler Example</h1>
    <div>
      <input
        autofocus
        type="search"
        :value="searchTerm"
        @input="onSearchChange"
        placeholder="Type to search..."
        :style="{ width: '100%' }"
        autocomplete="new-password"
      />
    </div>
    <div :style="{ marginTop: '10px' }">
      <button @click="() => setSearchAsyncThrottler.flush()">Flush</button>
    </div>
    <template v-if="error"
      ><div>Error: {{ error.message }}</div></template
    ><setSearchAsyncThrottler.Subscribe
      :selector="
        (state) => ({
          isExecuting: state.isExecuting,
          isPending: state.isPending,
          successCount: state.successCount,
        })
      "
      v-slot="{ isExecuting, isPending, successCount }"
      ><div>
        <p>API calls made: {{ successCount }}</p>
        <template v-if="results.length > 0"
          ><ul>
            <template v-for="(item, index) in results" :key="index"
              ><li>{{ item.title }}</li></template
            >
          </ul></template
        ><template v-if="isPending"><p>Pending...</p></template
        ><template v-else
          ><template v-if="isExecuting"><p>Executing...</p></template
          ><template v-else></template
        ></template></div></setSearchAsyncThrottler.Subscribe
    ><setSearchAsyncThrottler.Subscribe
      :selector="(state) => state"
      v-slot="state"
    >
      <pre :style="{ marginTop: '20px' }">{{
        JSON.stringify(state, null, 2)
      }}</pre>
    </setSearchAsyncThrottler.Subscribe>
  </div>
  <TanStackDevtools v-if="dev" :plugins="plugins" />
</template>
