// packages/lit-pacer/src/utils/subscribe.ts
import { shallow } from '@tanstack/store'
import type { ReactiveControllerHost } from 'lit'
import type { ReadonlyStore } from '@tanstack/store'

/** Selects state for a child host and releases its subscription on disconnection. */
export type LitPacerSubscribe<TState> = <TSelected>(
  host: ReactiveControllerHost,
  selector: (state: TState) => TSelected,
) => () => TSelected

export function createSubscribe<TState>(
  store: Pick<ReadonlyStore<TState>, 'state' | 'subscribe'>,
): LitPacerSubscribe<TState> {
  return (host, selector) => {
    let selected = selector(store.state)
    let subscription: { unsubscribe: () => void } | undefined
    const update = () => {
      const next = selector(store.state)
      if (shallow(selected, next)) return
      selected = next
      host.requestUpdate()
    }
    host.addController({
      hostConnected() {
        if (subscription) return
        update()
        subscription = store.subscribe(update)
      },
      hostUpdate: update,
      hostDisconnected() {
        subscription?.unsubscribe()
        subscription = undefined
      },
    })
    return () => selected
  }
}

// packages/svelte-pacer/src/utils/Subscribe.svelte
<script lang="ts" generics="TState, TSelected">
  import { untrack } from 'svelte'
  import { select } from './select.svelte'
  import type { ReadonlyStore } from '@tanstack/svelte-store'
  import type { Snippet } from 'svelte'

  let {
    store,
    selector,
    children,
  }: {
    store: Pick<ReadonlyStore<TState>, 'get' | 'subscribe'>
    selector: (state: TState) => TSelected
    children: Snippet<[TSelected]>
  } = $props()
  // Each utility creates a stable component bound to its own store.
  const selected = select(
    untrack(() => store),
    (state) => selector(state),
  )
</script>

{@render children(selected.current)}
